# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userSearch',
            fields=[
                ('login', models.CharField(max_length=120)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('avatar_url', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('public_repos', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
