# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchuser', '0002_auto_20170129_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
