# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchuser', '0003_auto_20170129_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='avatar_image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
