# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchuser', '0005_auto_20170129_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='avatar_image',
        ),
    ]
