# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchuser', '0006_remove_usersearch_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='updatedtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
