# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchuser', '0007_usersearch_updatedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='updatedtime',
            field=models.DateField(auto_now=True),
        ),
    ]
