# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('searchuser', '0009_auto_20170129_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='publish',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 29, 14, 49, 1, 343000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
