# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchuser', '0013_auto_20170129_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='queryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.TextField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
